updated for extra server if download from github fails.

diff --git a/AnberPorts/scripts/games/AM2R b/AnberPorts/scripts/games/AM2R
--- a/AnberPorts/scripts/games/AM2R
+++ b/AnberPorts/scripts/games/AM2R
@@ -3,8 +3,16 @@
 # Release: 1999    Genre: Action-adventure
 
 printf "\e[32mDownloading AM2R ..." > /dev/tty1
+
 wget -q 'https://github.com/krishenriksen/AnberPorts/raw/master/misc/am2r.zip'
-wget -q -O "../AM2R.sh" 'https://raw.githubusercontent.com/krishenriksen/AnberPorts/master/misc/AM2R.sh'
+if [[ $? -ne 0 ]]; then
+  printf "\e[32mDownloading failed, trying another server ..." > /dev/tty1
+
+  wget 'http://139.196.213.206/releases/anberports/misc/am2r.zip'
+  wget -q -O "../AM2R.sh" 'http://139.196.213.206/releases/anberports/misc/AM2R.sh'
+else
+  wget -q -O "../AM2R.sh" 'https://raw.githubusercontent.com/krishenriksen/AnberPorts/master/misc/AM2R.sh'
+fi
 
 printf "\e[32mExtracting ..." > /dev/tty1
 unzip -qq -o am2r.zip -d ../
diff --git a/AnberPorts/scripts/games/Alien-vs-Predator b/AnberPorts/scripts/games/Alien-vs-Predator
--- a/AnberPorts/scripts/games/Alien-vs-Predator
+++ b/AnberPorts/scripts/games/Alien-vs-Predator
@@ -3,8 +3,16 @@
 # Release: 2010    Genre: First-person shooter
 
 printf "\e[32mDownloading Alien vs. Predator ..." > /dev/tty1
+
 wget -q 'https://github.com/krishenriksen/AnberPorts/raw/master/misc/avp.zip'
-wget -q -O "../Alien vs. Predator.sh" 'https://raw.githubusercontent.com/krishenriksen/AnberPorts/master/misc/Alien%20vs.%20Predator.sh'
+if [[ $? -ne 0 ]]; then
+  printf "\e[32mDownloading failed, trying another server ..." > /dev/tty1
+
+  wget 'http://139.196.213.206/releases/anberports/misc/avp.zip'
+  wget -q -O "../Alien vs. Predator.sh" 'http://139.196.213.206/releases/anberports/misc/Alien%20vs.%20Predator.sh'
+else
+  wget -q -O "../Alien vs. Predator.sh" 'https://raw.githubusercontent.com/krishenriksen/AnberPorts/master/misc/Alien%20vs.%20Predator.sh'
+fi
 
 printf "\e[32mPlease copy games files to your Alien vs. Predator directory! ..." > /dev/tty1
 unzip -qq -o avp.zip -d ../
diff --git a/AnberPorts/scripts/games/Blood b/AnberPorts/scripts/games/Blood
--- a/AnberPorts/scripts/games/Blood
+++ b/AnberPorts/scripts/games/Blood
@@ -3,8 +3,16 @@
 # Release: 1997    Genre: First-person shooter
 
 printf "\e[32mDownloading Blood ..." > /dev/tty1
+
 wget -q 'https://github.com/krishenriksen/AnberPorts/raw/master/misc/blood.zip'
-wget -q -O "../Blood.sh" 'https://raw.githubusercontent.com/krishenriksen/AnberPorts/master/misc/Blood.sh'
+if [[ $? -ne 0 ]]; then
+  printf "\e[32mDownloading failed, trying another server ..." > /dev/tty1
+
+  wget 'http://139.196.213.206/releases/anberports/misc/blood.zip'
+  wget -q -O "../Blood.sh" 'http://139.196.213.206/releases/anberports/misc/Blood.sh'
+else
+  wget -q -O "../Blood.sh" 'https://raw.githubusercontent.com/krishenriksen/AnberPorts/master/misc/Blood.sh'
+fi
 
 printf "\e[32mPlease copy games files to your Blood directory! ..." > /dev/tty1
 unzip -qq -o blood.zip -d ../
diff --git a/AnberPorts/scripts/games/CannonBall b/AnberPorts/scripts/games/CannonBall
--- a/AnberPorts/scripts/games/CannonBall
+++ b/AnberPorts/scripts/games/CannonBall
@@ -3,8 +3,16 @@
 # Release: 1999    Genre: Racing
 
 printf "\e[32mDownloading CannonBall ..." > /dev/tty1
+
 wget -q 'https://github.com/krishenriksen/AnberPorts/raw/master/misc/cannonball.zip'
-wget -q -O "../Cannonball.sh" 'https://raw.githubusercontent.com/krishenriksen/AnberPorts/master/misc/Cannonball.sh'
+if [[ $? -ne 0 ]]; then
+  printf "\e[32mDownloading failed, trying another server ..." > /dev/tty1
+
+  wget 'http://139.196.213.206/releases/anberports/misc/cannonball.zip'
+  wget -q -O "../Cannonball.sh" 'http://139.196.213.206/releases/anberports/misc/Cannonball.sh'
+else
+  wget -q -O "../Cannonball.sh" 'https://raw.githubusercontent.com/krishenriksen/AnberPorts/master/misc/Cannonball.sh'
+fi
 
 printf "\e[32mExtracting ..." > /dev/tty1
 unzip -qq -o cannonball.zip -d ../
diff --git a/AnberPorts/scripts/games/Cave-Story b/AnberPorts/scripts/games/Cave-Story
--- a/AnberPorts/scripts/games/Cave-Story
+++ b/AnberPorts/scripts/games/Cave-Story
@@ -3,8 +3,16 @@
 # Release: 2004    Genre: Platform-adventure
 
 printf "\e[32mDownloading Cave-Story ..." > /dev/tty1
+
 wget -q 'https://github.com/krishenriksen/AnberPorts/raw/master/misc/cavestory.zip'
-wget -q -O "../Cave Story.sh" 'https://raw.githubusercontent.com/krishenriksen/AnberPorts/master/misc/Cave%20Story.sh'
+if [[ $? -ne 0 ]]; then
+  printf "\e[32mDownloading failed, trying another server ..." > /dev/tty1
+
+  wget 'http://139.196.213.206/releases/anberports/misc/cavestory.zip'
+  wget -q -O "../Cave Story.sh" 'http://139.196.213.206/releases/anberports/misc/Cave%20Story.sh'
+else
+  wget -q -O "../Cave Story.sh" 'https://raw.githubusercontent.com/krishenriksen/AnberPorts/master/misc/Cave%20Story.sh'
+fi
 
 printf "\e[32mExtracting ..." > /dev/tty1
 unzip -qq -o cavestory.zip -d ../
diff --git a/AnberPorts/scripts/games/Counter-Strike b/AnberPorts/scripts/games/Counter-Strike
--- a/AnberPorts/scripts/games/Counter-Strike
+++ b/AnberPorts/scripts/games/Counter-Strike
@@ -3,8 +3,16 @@
 # Release: 1999    Genre: Multiplayer first-person shooter
 
 printf "\e[32mDownloading Counter-Strike ..." > /dev/tty1
+
 wget -q 'https://github.com/krishenriksen/AnberPorts/raw/master/misc/half-life.zip'
-wget -q -O "../Counter-Strike.sh" 'https://raw.githubusercontent.com/krishenriksen/AnberPorts/master/misc/Counter-Strike.sh'
+if [[ $? -ne 0 ]]; then
+  printf "\e[32mDownloading failed, trying another server ..." > /dev/tty1
+
+  wget 'http://139.196.213.206/releases/anberports/misc/half-life.zip'
+  wget -q -O "../Counter-Strike.sh" 'http://139.196.213.206/releases/anberports/misc/Counter-Strike.sh'
+else
+  wget -q -O "../Counter-Strike.sh" 'https://raw.githubusercontent.com/krishenriksen/AnberPorts/master/misc/Counter-Strike.sh'
+fi
 
 printf "\e[32mExtracting ..." > /dev/tty1
 unzip -qq -o half-life.zip -d ../
diff --git a/AnberPorts/scripts/games/Descent b/AnberPorts/scripts/games/Descent
--- a/AnberPorts/scripts/games/Descent
+++ b/AnberPorts/scripts/games/Descent
@@ -3,8 +3,16 @@
 # Release: 1995    Genre: First-person shooter
 
 printf "\e[32mDownloading Descent ..." > /dev/tty1
+
 wget -q 'https://github.com/krishenriksen/AnberPorts/raw/master/misc/descent.zip'
-wget -q -O "../Descent.sh" 'https://raw.githubusercontent.com/krishenriksen/AnberPorts/master/misc/Descent.sh'
+if [[ $? -ne 0 ]]; then
+  printf "\e[32mDownloading failed, trying another server ..." > /dev/tty1
+
+  wget 'http://139.196.213.206/releases/anberports/misc/descent.zip'
+  wget -q -O "../Descent.sh" 'http://139.196.213.206/releases/anberports/misc/Descent.sh'
+else
+  wget -q -O "../Descent.sh" 'https://raw.githubusercontent.com/krishenriksen/AnberPorts/master/misc/Descent.sh'
+fi
 
 printf "\e[32mExtracting ..." > /dev/tty1
 unzip -qq -o descent.zip -d ../
diff --git a/AnberPorts/scripts/games/Descent2 b/AnberPorts/scripts/games/Descent2
--- a/AnberPorts/scripts/games/Descent2
+++ b/AnberPorts/scripts/games/Descent2
@@ -3,8 +3,16 @@
 # Release: 1996    Genre: First-person shooter
 
 printf "\e[32mDownloading Descent 2 ..." > /dev/tty1
+
 wget -q 'https://github.com/krishenriksen/AnberPorts/raw/master/misc/descent2.zip'
-wget -q -O "../Descent 2.sh" 'https://raw.githubusercontent.com/krishenriksen/AnberPorts/master/misc/Descent%202.sh'
+if [[ $? -ne 0 ]]; then
+  printf "\e[32mDownloading failed, trying another server ..." > /dev/tty1
+
+  wget 'http://139.196.213.206/releases/anberports/misc/descent2.zip'
+  wget -q -O "../Descent 2.sh" 'http://139.196.213.206/releases/anberports/misc/Descent%202.sh'
+else
+  wget -q -O "../Descent 2.sh" 'https://raw.githubusercontent.com/krishenriksen/AnberPorts/master/misc/Descent%202.sh'
+fi
 
 printf "\e[32mExtracting ..." > /dev/tty1
 unzip -qq -o descent2.zip -d ../
diff --git a/AnberPorts/scripts/games/Diablo1 b/AnberPorts/scripts/games/Diablo1
--- a/AnberPorts/scripts/games/Diablo1
+++ b/AnberPorts/scripts/games/Diablo1
@@ -3,8 +3,16 @@
 # Release: 1997    Genre: Role-playing hack-and-slash
 
 printf "\e[32mDownloading Diablo 1 ..." > /dev/tty1
+
 wget -q 'https://github.com/krishenriksen/AnberPorts/raw/master/misc/diablo1.zip'
-wget -q -O "../Diablo 1.sh" 'https://raw.githubusercontent.com/krishenriksen/AnberPorts/master/misc/Diablo%201.sh'
+if [[ $? -ne 0 ]]; then
+  printf "\e[32mDownloading failed, trying another server ..." > /dev/tty1
+
+  wget 'http://139.196.213.206/releases/anberports/misc/diablo1.zip'
+  wget -q -O "../Diablo 1.sh" 'http://139.196.213.206/releases/anberports/misc/Diablo%201.sh'
+else
+  wget -q -O "../Diablo 1.sh" 'https://raw.githubusercontent.com/krishenriksen/AnberPorts/master/misc/Diablo%201.sh'
+fi
 
 printf "\e[32mExtracting ..." > /dev/tty1
 unzip -qq -o diablo1.zip -d ../
diff --git a/AnberPorts/scripts/games/Digger b/AnberPorts/scripts/games/Digger
--- a/AnberPorts/scripts/games/Digger
+++ b/AnberPorts/scripts/games/Digger
@@ -3,8 +3,17 @@
 # Release: 1983    Genre: Platform
 
 printf "\e[32mDownloading Digger ..." > /dev/tty1
+
 wget -q 'https://github.com/krishenriksen/AnberPorts/raw/master/misc/digger.zip'
-wget -q -O "../Digger.sh" 'https://raw.githubusercontent.com/krishenriksen/AnberPorts/master/misc/Digger.sh'
+if [[ $? -ne 0 ]]; then
+  printf "\e[32mDownloading failed, trying another server ..." > /dev/tty1
+
+  wget 'http://139.196.213.206/releases/anberports/misc/digger.zip'
+  wget -q -O "../Digger.sh" 'http://139.196.213.206/releases/anberports/misc/Digger.sh'
+else
+  wget -q -O "../Digger.sh" 'https://raw.githubusercontent.com/krishenriksen/AnberPorts/master/misc/Digger.sh'
+fi
+
 chmod +x "../Digger.sh"
 
 printf "\e[32mExtracting ..." > /dev/tty1
diff --git a/AnberPorts/scripts/games/Doom1 b/AnberPorts/scripts/games/Doom1
--- a/AnberPorts/scripts/games/Doom1
+++ b/AnberPorts/scripts/games/Doom1
@@ -3,8 +3,16 @@
 # Release: 1993    Genre: First-person shooter
 
 printf "\e[32mDownloading Doom 1 ..." > /dev/tty1
+
 wget -q 'https://github.com/krishenriksen/AnberPorts/raw/master/misc/doom1.zip'
-wget -q -O "../Doom.sh" 'https://raw.githubusercontent.com/krishenriksen/AnberPorts/master/misc/Doom.sh'
+if [[ $? -ne 0 ]]; then
+  printf "\e[32mDownloading failed, trying another server ..." > /dev/tty1
+
+  wget 'http://139.196.213.206/releases/anberports/misc/doom1.zip'
+  wget -q -O "../Doom.sh" 'http://139.196.213.206/releases/anberports/misc/Doom.sh'
+else
+  wget -q -O "../Doom.sh" 'https://raw.githubusercontent.com/krishenriksen/AnberPorts/master/misc/Doom.sh'
+fi
 
 printf "\e[32mExtracting ..." > /dev/tty1
 unzip -qq -o doom1.zip -d ../
diff --git a/AnberPorts/scripts/games/Doom2 b/AnberPorts/scripts/games/Doom2
--- a/AnberPorts/scripts/games/Doom2
+++ b/AnberPorts/scripts/games/Doom2
@@ -3,8 +3,16 @@
 # Release: 1994    Genre: First-person shooter
 
 printf "\e[32mDownloading Doom 2 ..." > /dev/tty1
+
 wget -q 'https://github.com/krishenriksen/AnberPorts/raw/master/misc/doom2.zip'
-wget -q -O "../Doom 2.sh" 'https://raw.githubusercontent.com/krishenriksen/AnberPorts/master/misc/Doom%202.sh'
+if [[ $? -ne 0 ]]; then
+  printf "\e[32mDownloading failed, trying another server ..." > /dev/tty1
+
+  wget 'http://139.196.213.206/releases/anberports/misc/doom2.zip'
+  wget -q -O "../Doom 2.sh" 'http://139.196.213.206/releases/anberports/misc/Doom%202.sh'
+else
+  wget -q -O "../Doom 2.sh" 'https://raw.githubusercontent.com/krishenriksen/AnberPorts/master/misc/Doom%202.sh'
+fi
 
 printf "\e[32mPlease copy 'Doom2.wad' to your doom2 directory! ..." > /dev/tty1
 unzip -qq -o doom2.zip -d ../
diff --git a/AnberPorts/scripts/games/Eduke32 b/AnberPorts/scripts/games/Eduke32
--- a/AnberPorts/scripts/games/Eduke32
+++ b/AnberPorts/scripts/games/Eduke32
@@ -3,8 +3,16 @@
 # Release: 1996    Genre: First-person shooter
 
 printf "\e[32mDownloading Eduke32 ..." > /dev/tty1
+
 wget -q 'https://github.com/krishenriksen/AnberPorts/raw/master/misc/eduke32.zip'
-wget -q -O "../Duke Nukem 3D.sh" 'https://raw.githubusercontent.com/krishenriksen/AnberPorts/master/misc/Duke%20Nukem%203D.sh'
+if [[ $? -ne 0 ]]; then
+  printf "\e[32mDownloading failed, trying another server ..." > /dev/tty1
+
+  wget 'http://139.196.213.206/releases/anberports/misc/eduke32.zip'
+  wget -q -O "../Duke Nukem 3D.sh" 'http://139.196.213.206/releases/anberports/misc/Duke%20Nukem%203D.sh'
+else
+  wget -q -O "../Duke Nukem 3D.sh" 'https://raw.githubusercontent.com/krishenriksen/AnberPorts/master/misc/Duke%20Nukem%203D.sh'
+fi
 
 printf "\e[32mPlease copy 'DUKE3D.GRP' to your eduke32 directory! ..." > /dev/tty1
 unzip -qq -o eduke32.zip -d ../
diff --git a/AnberPorts/scripts/games/Exhumed b/AnberPorts/scripts/games/Exhumed
--- a/AnberPorts/scripts/games/Exhumed
+++ b/AnberPorts/scripts/games/Exhumed
@@ -3,8 +3,16 @@
 # Release: 1996    Genre: First-person shooter
 
 printf "\e[32mDownloading Exhumed / PowerSlave ..." > /dev/tty1
+
 wget -q 'https://github.com/krishenriksen/AnberPorts/raw/master/misc/exhumed.zip'
-wget -q -O "../Exhumed.sh" 'https://raw.githubusercontent.com/krishenriksen/AnberPorts/master/misc/Exhumed.sh'
+if [[ $? -ne 0 ]]; then
+  printf "\e[32mDownloading failed, trying another server ..." > /dev/tty1
+
+  wget 'http://139.196.213.206/releases/anberports/misc/exhumed.zip'
+  wget -q -O "../Exhumed.sh" 'http://139.196.213.206/releases/anberports/misc/Exhumed.sh'
+else
+  wget -q -O "../Exhumed.sh" 'https://raw.githubusercontent.com/krishenriksen/AnberPorts/master/misc/Exhumed.sh'
+fi
 
 printf "\e[32mPlease copy games files to your Exhumed directory! ..." > /dev/tty1
 unzip -qq -o exhumed.zip -d ../
diff --git a/AnberPorts/scripts/games/Flashback b/AnberPorts/scripts/games/Flashback
--- a/AnberPorts/scripts/games/Flashback
+++ b/AnberPorts/scripts/games/Flashback
@@ -3,8 +3,16 @@
 # Release: 1992    Genre: First-person shooter
 
 printf "\e[32mDownloading Flashback ..." > /dev/tty1
+
 wget -q 'https://github.com/krishenriksen/AnberPorts/raw/master/misc/flashback.zip'
-wget -q -O "../Flashback.sh" 'https://raw.githubusercontent.com/krishenriksen/AnberPorts/master/misc/Flashback.sh'
+if [[ $? -ne 0 ]]; then
+  printf "\e[32mDownloading failed, trying another server ..." > /dev/tty1
+
+  wget 'http://139.196.213.206/releases/anberports/misc/flashback.zip'
+  wget -q -O "../Flashback.sh" 'http://139.196.213.206/releases/anberports/misc/Flashback.sh'
+else
+  wget -q -O "../Flashback.sh" 'https://raw.githubusercontent.com/krishenriksen/AnberPorts/master/misc/Flashback.sh'
+fi
 
 printf "\e[32mExtracting ..." > /dev/tty1
 unzip -qq -o flashback.zip -d ../
diff --git a/AnberPorts/scripts/games/Half-Life b/AnberPorts/scripts/games/Half-Life
--- a/AnberPorts/scripts/games/Half-Life
+++ b/AnberPorts/scripts/games/Half-Life
@@ -3,8 +3,16 @@
 # Release: 1998    Genre: First-person shooter
 
 printf "\e[32mDownloading Half-Life ..." > /dev/tty1
+
 wget -q 'https://github.com/krishenriksen/AnberPorts/raw/master/misc/half-life.zip'
-wget -q -O "../Half-Life.sh" 'https://raw.githubusercontent.com/krishenriksen/AnberPorts/master/misc/Half-Life.sh'
+if [[ $? -ne 0 ]]; then
+  printf "\e[32mDownloading failed, trying another server ..." > /dev/tty1
+
+  wget 'http://139.196.213.206/releases/anberports/misc/half-life.zip'
+  wget -q -O "../Half-Life.sh" 'http://139.196.213.206/releases/anberports/misc/Half-Life.sh'
+else
+  wget -q -O "../Half-Life.sh" 'https://raw.githubusercontent.com/krishenriksen/AnberPorts/master/misc/Half-Life.sh'
+fi
 
 printf "\e[32mExtracting ..." > /dev/tty1
 unzip -qq -o half-life.zip -d ../
diff --git a/AnberPorts/scripts/games/Half-Life-Blue-Shift b/AnberPorts/scripts/games/Half-Life-Blue-Shift
--- a/AnberPorts/scripts/games/Half-Life-Blue-Shift
+++ b/AnberPorts/scripts/games/Half-Life-Blue-Shift
@@ -3,8 +3,16 @@
 # Release: 2001    Genre: First-person shooter
 
 printf "\e[32mDownloading Half-Life: Blue Shift ..." > /dev/tty1
+
 wget -q 'https://github.com/krishenriksen/AnberPorts/raw/master/misc/half-life.zip'
-wget -q -O "../Half-Life Blue Shift.sh" 'https://raw.githubusercontent.com/krishenriksen/AnberPorts/master/misc/Half-Life%20Blue%20Shift.sh'
+if [[ $? -ne 0 ]]; then
+  printf "\e[32mDownloading failed, trying another server ..." > /dev/tty1
+
+  wget 'http://139.196.213.206/releases/anberports/misc/half-life.zip'
+  wget -q -O "../Half-Life Blue Shift.sh" 'http://139.196.213.206/releases/anberports/misc/Half-Life%20Blue%20Shift.sh'
+else
+  wget -q -O "../Half-Life Blue Shift.sh" 'https://raw.githubusercontent.com/krishenriksen/AnberPorts/master/misc/Half-Life%20Blue%20Shift.sh'
+fi
 
 printf "\e[32mExtracting ..." > /dev/tty1
 unzip -qq -o half-life.zip -d ../
diff --git a/AnberPorts/scripts/games/Jedi-Academy b/AnberPorts/scripts/games/Jedi-Academy
--- a/AnberPorts/scripts/games/Jedi-Academy
+++ b/AnberPorts/scripts/games/Jedi-Academy
@@ -3,8 +3,16 @@
 # Release: 2003    Genre: First- and third-person shooter
 
 printf "\e[32mDownloading Star Wars Jedi Knight: Jedi Academy ..." > /dev/tty1
+
 wget -q 'https://github.com/krishenriksen/AnberPorts/raw/master/misc/jedi-academy.zip'
-wget -q -O "../Star Wars Jedi Knight - Jedi Academy.sh" 'https://raw.githubusercontent.com/krishenriksen/AnberPorts/master/misc/Star%20Wars%20Jedi%20Knight%20-%20Jedi%20Academy.sh'
+if [[ $? -ne 0 ]]; then
+  printf "\e[32mDownloading failed, trying another server ..." > /dev/tty1
+
+  wget 'http://139.196.213.206/releases/anberports/misc/jedi-academy.zip'
+  wget -q -O "../Star Wars Jedi Knight - Jedi Academy.sh" 'http://139.196.213.206/releases/anberports/misc/Star%20Wars%20Jedi%20Knight%20-%20Jedi%20Academy.sh'
+else
+  wget -q -O "../Star Wars Jedi Knight - Jedi Academy.sh" 'https://raw.githubusercontent.com/krishenriksen/AnberPorts/master/misc/Star%20Wars%20Jedi%20Knight%20-%20Jedi%20Academy.sh'
+fi
 
 printf "\e[32mPlease copy *.pk3 files to your JediAcademy/base directory! ..." > /dev/tty1
 unzip -qq -o jedi-academy.zip -d ../
diff --git a/AnberPorts/scripts/games/Keen b/AnberPorts/scripts/games/Keen
--- a/AnberPorts/scripts/games/Keen
+++ b/AnberPorts/scripts/games/Keen
@@ -3,8 +3,16 @@
 # Release: 1990    Genre: Side-scrolling platform
 
 printf "\e[32mDownloading Commander Keen ..." > /dev/tty1
+
 wget -q 'https://github.com/krishenriksen/AnberPorts/raw/master/misc/keen.zip'
-wget -q -O "../Commander Genius.sh" 'https://raw.githubusercontent.com/krishenriksen/AnberPorts/master/misc/Commander%20Genius.sh'
+if [[ $? -ne 0 ]]; then
+  printf "\e[32mDownloading failed, trying another server ..." > /dev/tty1
+
+  wget 'http://139.196.213.206/releases/anberports/misc/keen.zip'
+  wget -q -O "../Commander Genius.sh" 'http://139.196.213.206/releases/anberports/misc/Commander%20Genius.sh'
+else
+  wget -q -O "../Commander Genius.sh" 'https://raw.githubusercontent.com/krishenriksen/AnberPorts/master/misc/Commander%20Genius.sh'
+fi
 
 printf "\e[32mPlease copy 'keen' folders to your cgenius/games directory! ..." > /dev/tty1
 unzip -qq -o keen.zip -d ../
diff --git a/AnberPorts/scripts/games/Maldita-Castilla b/AnberPorts/scripts/games/Maldita-Castilla
--- a/AnberPorts/scripts/games/Maldita-Castilla
+++ b/AnberPorts/scripts/games/Maldita-Castilla
@@ -3,8 +3,16 @@
 # Release: 2012    Genre: Arcade action
 
 printf "\e[32mDownloading Maldita Castilla ..." > /dev/tty1
+
 wget -q 'https://github.com/krishenriksen/AnberPorts/raw/master/misc/maldita-castilla.zip'
-wget -q -O "../Maldita Castilla.sh" 'https://raw.githubusercontent.com/krishenriksen/AnberPorts/master/misc/Maldita%20Castilla.sh'
+if [[ $? -ne 0 ]]; then
+  printf "\e[32mDownloading failed, trying another server ..." > /dev/tty1
+
+  wget 'http://139.196.213.206/releases/anberports/misc/maldita-castilla.zip'
+  wget -q -O "../Maldita Castilla.sh" 'http://139.196.213.206/releases/anberports/misc/Maldita%20Castilla.sh'
+else
+  wget -q -O "../Maldita Castilla.sh" 'https://raw.githubusercontent.com/krishenriksen/AnberPorts/master/misc/Maldita%20Castilla.sh'
+fi
 
 printf "\e[32mExtracting ..." > /dev/tty1
 unzip -qq -o maldita-castilla.zip -d ../
diff --git a/AnberPorts/scripts/games/NAM b/AnberPorts/scripts/games/NAM
--- a/AnberPorts/scripts/games/NAM
+++ b/AnberPorts/scripts/games/NAM
@@ -3,8 +3,16 @@
 # Release: 1998    Genre: First-person shooter
 
 printf "\e[32mDownloading NAM ..." > /dev/tty1
+
 wget -q 'https://github.com/krishenriksen/AnberPorts/raw/master/misc/nam.zip'
-wget -q -O "../NAM.sh" 'https://raw.githubusercontent.com/krishenriksen/AnberPorts/master/misc/NAM.sh'
+if [[ $? -ne 0 ]]; then
+  printf "\e[32mDownloading failed, trying another server ..." > /dev/tty1
+
+  wget 'http://139.196.213.206/releases/anberports/misc/nam.zip'
+  wget -q -O "../NAM.sh" 'http://139.196.213.206/releases/anberports/misc/NAM.sh'
+else
+  wget -q -O "../NAM.sh" 'https://raw.githubusercontent.com/krishenriksen/AnberPorts/master/misc/NAM.sh'
+fi
 
 printf "\e[32mPlease copy games files to your NAM directory! ..." > /dev/tty1
 unzip -qq -o nam.zip -d ../
diff --git a/AnberPorts/scripts/games/Prince-of-Persia b/AnberPorts/scripts/games/Prince-of-Persia
--- a/AnberPorts/scripts/games/Prince-of-Persia
+++ b/AnberPorts/scripts/games/Prince-of-Persia
@@ -3,8 +3,16 @@
 # Release: 1999    Genre: Side-scrolling platform
 
 printf "\e[32mDownloading Prince of Persia ..." > /dev/tty1
+
 wget -q 'https://github.com/krishenriksen/AnberPorts/raw/master/misc/sdlpop.zip'
-wget -q -O "../Prince of Persia.sh" 'https://raw.githubusercontent.com/krishenriksen/AnberPorts/master/misc/Prince%20of%20Persia.sh'
+if [[ $? -ne 0 ]]; then
+  printf "\e[32mDownloading failed, trying another server ..." > /dev/tty1
+
+  wget 'http://139.196.213.206/releases/anberports/misc/sdlpop.zip'
+  wget -q -O "../Prince of Persia.sh" 'http://139.196.213.206/releases/anberports/misc/Prince%20of%20Persia.sh'
+else
+  wget -q -O "../Prince of Persia.sh" 'https://raw.githubusercontent.com/krishenriksen/AnberPorts/master/misc/Prince%20of%20Persia.sh'
+fi
 
 printf "\e[32mExtracting ..." > /dev/tty1
 unzip -qq -o sdlpop.zip -d ../
diff --git a/AnberPorts/scripts/games/Quake1 b/AnberPorts/scripts/games/Quake1
--- a/AnberPorts/scripts/games/Quake1
+++ b/AnberPorts/scripts/games/Quake1
@@ -3,8 +3,16 @@
 # Release: 1996    Genre: First-person shooter
 
 printf "\e[32mDownloading Quake 1 ..." > /dev/tty1
+
 wget -q 'https://github.com/krishenriksen/AnberPorts/raw/master/misc/quake1.zip'
-wget -q -O "../Quake 1.sh" 'https://raw.githubusercontent.com/krishenriksen/AnberPorts/master/misc/Quake%201.sh'
+if [[ $? -ne 0 ]]; then
+  printf "\e[32mDownloading failed, trying another server ..." > /dev/tty1
+
+  wget 'http://139.196.213.206/releases/anberports/misc/quake1.zip'
+  wget -q -O "../Quake 1.sh" 'http://139.196.213.206/releases/anberports/misc/Quake%201.sh'
+else
+  wget -q -O "../Quake 1.sh" 'https://raw.githubusercontent.com/krishenriksen/AnberPorts/master/misc/Quake%201.sh'
+fi
 
 printf "\e[32mPlease copy 'PAK0.PAK' to your quake1 directory! ..." > /dev/tty1
 unzip -qq -o quake1.zip -d ../
diff --git a/AnberPorts/scripts/games/Quake2 b/AnberPorts/scripts/games/Quake2
--- a/AnberPorts/scripts/games/Quake2
+++ b/AnberPorts/scripts/games/Quake2
@@ -3,8 +3,16 @@
 # Release: 1997    Genre: First-person shooter
 
 printf "\e[32mDownloading Quake 2 ..." > /dev/tty1
+
 wget -q 'https://github.com/krishenriksen/AnberPorts/raw/master/misc/quake2.zip'
-wget -q -O "../Quake 2.sh" 'https://raw.githubusercontent.com/krishenriksen/AnberPorts/master/misc/Quake%202.sh'
+if [[ $? -ne 0 ]]; then
+  printf "\e[32mDownloading failed, trying another server ..." > /dev/tty1
+
+  wget 'http://139.196.213.206/releases/anberports/misc/quake2.zip'
+  wget -q -O "../Quake 2.sh" 'http://139.196.213.206/releases/anberports/misc/Quake%202.sh'
+else
+  wget -q -O "../Quake 2.sh" 'https://raw.githubusercontent.com/krishenriksen/AnberPorts/master/misc/Quake%202.sh'
+fi
 
 printf "\e[32mPlease copy '*.pak' to your quake2/baseq2 directory! ..." > /dev/tty1
 unzip -qq -o quake2.zip -d ../
diff --git a/AnberPorts/scripts/games/Quake3 b/AnberPorts/scripts/games/Quake3
--- a/AnberPorts/scripts/games/Quake3
+++ b/AnberPorts/scripts/games/Quake3
@@ -3,8 +3,16 @@
 # Release: 1999    Genre: First-person shooter
 
 printf "\e[32mDownloading Quake 3 ..." > /dev/tty1
+
 wget -q 'https://github.com/krishenriksen/AnberPorts/raw/master/misc/quake3.zip'
-wget -q -O "../Quake 3.sh" 'https://raw.githubusercontent.com/krishenriksen/AnberPorts/master/misc/Quake%203.sh'
+if [[ $? -ne 0 ]]; then
+  printf "\e[32mDownloading failed, trying another server ..." > /dev/tty1
+
+  wget 'http://139.196.213.206/releases/anberports/misc/quake3.zip'
+  wget -q -O "../Quake 3.sh" 'http://139.196.213.206/releases/anberports/misc/Quake%203.sh'
+else
+  wget -q -O "../Quake 3.sh" 'https://raw.githubusercontent.com/krishenriksen/AnberPorts/master/misc/Quake%203.sh'
+fi
 
 printf "\e[32mPlease copy '*.pk3' to your quake3/baseq3 directory! ..." > /dev/tty1
 unzip -qq -o quake3.zip -d ../
diff --git a/AnberPorts/scripts/games/Redneck-Rampage b/AnberPorts/scripts/games/Redneck-Rampage
--- a/AnberPorts/scripts/games/Redneck-Rampage
+++ b/AnberPorts/scripts/games/Redneck-Rampage
@@ -3,8 +3,16 @@
 # Release: 1997    Genre: First-person shooter game
 
 printf "\e[32mDownloading Redneck Rampage ..." > /dev/tty1
+
 wget -q 'https://github.com/krishenriksen/AnberPorts/raw/master/misc/redneck-rampage.zip'
-wget -q -O "../Redneck Rampage.sh" 'https://raw.githubusercontent.com/krishenriksen/AnberPorts/master/misc/Redneck%20Rampage.sh'
+if [[ $? -ne 0 ]]; then
+  printf "\e[32mDownloading failed, trying another server ..." > /dev/tty1
+
+  wget 'http://139.196.213.206/releases/anberports/misc/redneck-rampage.zip'
+  wget -q -O "../Redneck Rampage.sh" 'http://139.196.213.206/releases/anberports/misc/Redneck%20Rampage.sh'
+else
+  wget -q -O "../Redneck Rampage.sh" 'https://raw.githubusercontent.com/krishenriksen/AnberPorts/master/misc/Redneck%20Rampage.sh'
+fi
 
 printf "\e[32mPlease copy game files to your Redneck Rampage directory! ..." > /dev/tty1
 unzip -qq -o redneck-rampage.zip -d ../
diff --git a/AnberPorts/scripts/games/Redneck-Rampage-Rides-Again b/AnberPorts/scripts/games/Redneck-Rampage-Rides-Again
--- a/AnberPorts/scripts/games/Redneck-Rampage-Rides-Again
+++ b/AnberPorts/scripts/games/Redneck-Rampage-Rides-Again
@@ -3,8 +3,16 @@
 # Release: 1998    Genre: First-person shooter
 
 printf "\e[32mDownloading Redneck Rampage Rides Again ..." > /dev/tty1
+
 wget -q 'https://github.com/krishenriksen/AnberPorts/raw/master/misc/redneck-rampage-rides-again.zip'
-wget -q -O "../Redneck Rampage Rides Again.sh" 'https://raw.githubusercontent.com/krishenriksen/AnberPorts/master/misc/Redneck%20Rampage%20Rides%20Again.sh'
+if [[ $? -ne 0 ]]; then
+  printf "\e[32mDownloading failed, trying another server ..." > /dev/tty1
+
+  wget 'http://139.196.213.206/releases/anberports/misc/redneck-rampage-rides-again.zip'
+  wget -q -O "../Redneck Rampage Rides Again.sh" 'http://139.196.213.206/releases/anberports/misc/Redneck%20Rampage%20Rides%20Again.sh'
+else
+  wget -q -O "../Redneck Rampage Rides Again.sh" 'https://raw.githubusercontent.com/krishenriksen/AnberPorts/master/misc/Redneck%20Rampage%20Rides%20Again.sh'
+fi
 
 printf "\e[32mPlease copy game files to your Redneck Rampage Rides Again directory! ..." > /dev/tty1
 unzip -qq -o redneck-rampage-rides-again.zip -d ../
diff --git a/AnberPorts/scripts/games/Rick-Dangerous b/AnberPorts/scripts/games/Rick-Dangerous
--- a/AnberPorts/scripts/games/Rick-Dangerous
+++ b/AnberPorts/scripts/games/Rick-Dangerous
@@ -3,8 +3,16 @@
 # Release: 1989    Genre: Side-scrolling platform
 
 printf "\e[32mDownloading Rick Dangerous ..." > /dev/tty1
+
 wget -q 'https://github.com/krishenriksen/AnberPorts/raw/master/misc/rick-dangerous.zip'
-wget -q -O "../Rick Dangerous.sh" 'https://raw.githubusercontent.com/krishenriksen/AnberPorts/master/misc/Rick%20Dangerous.sh'
+if [[ $? -ne 0 ]]; then
+  printf "\e[32mDownloading failed, trying another server ..." > /dev/tty1
+
+  wget 'http://139.196.213.206/releases/anberports/misc/rick-dangerous.zip'
+  wget -q -O "../Rick Dangerous.sh" 'http://139.196.213.206/releases/anberports/misc/Rick%20Dangerous.sh'
+else
+  wget -q -O "../Rick Dangerous.sh" 'https://raw.githubusercontent.com/krishenriksen/AnberPorts/master/misc/Rick%20Dangerous.sh'
+fi
 
 printf "\e[32mExtracting ..." > /dev/tty1
 unzip -qq -o rick-dangerous.zip -d ../
@@ -14,4 +22,3 @@ printf "\e[32mCleaning Up ..." > /dev/tty1
 rm -rf rick-dangerous.zip
 
 printf "\e[32mEnjoy! ..." > /dev/tty1
-sleep 3
diff --git a/AnberPorts/scripts/games/Shadow-Warrior b/AnberPorts/scripts/games/Shadow-Warrior
--- a/AnberPorts/scripts/games/Shadow-Warrior
+++ b/AnberPorts/scripts/games/Shadow-Warrior
@@ -3,8 +3,16 @@
 # Release: 1997    Genre: First-person shooter
 
 printf "\e[32mDownloading Shadow Warrior ..." > /dev/tty1
+
 wget -q 'https://github.com/krishenriksen/AnberPorts/raw/master/misc/shadow-warrior.zip'
-wget -q -O "../Shadow Warrior.sh" 'https://raw.githubusercontent.com/krishenriksen/AnberPorts/master/misc/Shadow%20Warrior.sh'
+if [[ $? -ne 0 ]]; then
+  printf "\e[32mDownloading failed, trying another server ..." > /dev/tty1
+
+  wget 'http://139.196.213.206/releases/anberports/misc/shadow-warrior.zip'
+  wget -q -O "../Shadow Warrior.sh" 'http://139.196.213.206/releases/anberports/misc/Shadow%20Warrior.sh'
+else
+  wget -q -O "../Shadow Warrior.sh" 'https://raw.githubusercontent.com/krishenriksen/AnberPorts/master/misc/Shadow%20Warrior.sh'
+fi
 
 printf "\e[32mPlease copy game files to your shadow-warrior directory! ..." > /dev/tty1
 unzip -qq -o shadow-warrior.zip -d ../
diff --git a/AnberPorts/scripts/games/Sonic-Robo-Blast-2 b/AnberPorts/scripts/games/Sonic-Robo-Blast-2
--- a/AnberPorts/scripts/games/Sonic-Robo-Blast-2
+++ b/AnberPorts/scripts/games/Sonic-Robo-Blast-2
@@ -3,8 +3,16 @@
 # Release: 1999    Genre: First-person shooter
 
 printf "\e[32mDownloading Sonic Robo Blast 2 ..." > /dev/tty1
+
 wget -q 'https://github.com/krishenriksen/AnberPorts/raw/master/misc/sonic-robo-blast-2.zip'
-wget -q -O "../Sonic Robo Blast 2.sh" 'https://raw.githubusercontent.com/krishenriksen/AnberPorts/master/misc/Sonic%20Robo%20Blast%202.sh'
+if [[ $? -ne 0 ]]; then
+  printf "\e[32mDownloading failed, trying another server ..." > /dev/tty1
+
+  wget 'http://139.196.213.206/releases/anberports/misc/sonic-robo-blast-2.zip'
+  wget -q -O "../Sonic Robo Blast 2.sh" 'http://139.196.213.206/releases/anberports/misc/Sonic%20Robo%20Blast%202.sh'
+else
+  wget -q -O "../Sonic Robo Blast 2.sh" 'https://raw.githubusercontent.com/krishenriksen/AnberPorts/master/misc/Sonic%20Robo%20Blast%202.sh'
+fi
 
 printf "\e[32mPlease copy games files to your Sonic Robo Blast 2 directory! ..." > /dev/tty1
 unzip -qq -o sonic-robo-blast-2.zip -d ../
diff --git a/AnberPorts/scripts/games/Sonic-Robo-Blast-2-Kart b/AnberPorts/scripts/games/Sonic-Robo-Blast-2-Kart
--- a/AnberPorts/scripts/games/Sonic-Robo-Blast-2-Kart
+++ b/AnberPorts/scripts/games/Sonic-Robo-Blast-2-Kart
@@ -3,10 +3,21 @@
 # Release: 2018    Genre: First-person shooter
 
 printf "\e[32mDownloading Sonic Robo Blast 2 Kart ..." > /dev/tty1
+
 wget -q 'https://github.com/krishenriksen/AnberPorts/raw/master/misc/sonic-robo-blast-2-kart.zip'
-wget -q 'https://github.com/krishenriksen/AnberPorts/raw/master/misc/sonic-robo-blast-2-kart.z01'
-wget -q 'https://github.com/krishenriksen/AnberPorts/raw/master/misc/sonic-robo-blast-2-kart.z02'
-wget -q -O "../Sonic Robo Blast 2 Kart.sh" 'https://raw.githubusercontent.com/krishenriksen/AnberPorts/master/misc/Sonic%20Robo%20Blast%202%20Kart.sh'
+if [[ $? -ne 0 ]]; then
+  printf "\e[32mDownloading failed, trying another server ..." > /dev/tty1
+
+  wget 'http://139.196.213.206/releases/anberports/misc/sonic-robo-blast-2-kart.zip'
+  wget -q 'http://139.196.213.206/releases/anberports/misc/sonic-robo-blast-2-kart.z01'
+  wget -q 'http://139.196.213.206/releases/anberports/misc/sonic-robo-blast-2-kart.z02'
+  wget -q -O "../Sonic Robo Blast 2 Kart.sh" 'http://139.196.213.206/releases/anberports/misc/Sonic%20Robo%20Blast%202%20Kart.sh'
+else
+  wget -q 'https://github.com/krishenriksen/AnberPorts/raw/master/misc/sonic-robo-blast-2-kart.z01'
+  wget -q 'https://github.com/krishenriksen/AnberPorts/raw/master/misc/sonic-robo-blast-2-kart.z02'
+  wget -q -O "../Sonic Robo Blast 2 Kart.sh" 'https://raw.githubusercontent.com/krishenriksen/AnberPorts/master/misc/Sonic%20Robo%20Blast%202%20Kart.sh'
+fi
+
 chmod +x "../Sonic Robo Blast 2 Kart.sh"
 
 printf "\e[32mExtracting ..." > /dev/tty1
diff --git a/AnberPorts/scripts/games/Spelunky b/AnberPorts/scripts/games/Spelunky
--- a/AnberPorts/scripts/games/Spelunky
+++ b/AnberPorts/scripts/games/Spelunky
@@ -3,8 +3,16 @@
 # Release: 2008    Genre: Side-scrolling platform
 
 printf "\e[32mDownloading Spelunky ..." > /dev/tty1
+
 wget -q 'https://github.com/krishenriksen/AnberPorts/raw/master/misc/spelunky.zip'
-wget -q -O "../Spelunky.sh" 'https://raw.githubusercontent.com/krishenriksen/AnberPorts/master/misc/Spelunky.sh'
+if [[ $? -ne 0 ]]; then
+  printf "\e[32mDownloading failed, trying another server ..." > /dev/tty1
+
+  wget 'http://139.196.213.206/releases/anberports/misc/spelunky.zip'
+  wget -q -O "../Spelunky.sh" 'http://139.196.213.206/releases/anberports/misc/Spelunky.sh'
+else
+  wget -q -O "../Spelunky.sh" 'https://raw.githubusercontent.com/krishenriksen/AnberPorts/master/misc/Spelunky.sh'
+fi
 
 printf "\e[32mExtracting ..." > /dev/tty1
 unzip -qq -o spelunky.zip -d ../
diff --git a/AnberPorts/scripts/games/Super-Crate-Box b/AnberPorts/scripts/games/Super-Crate-Box
--- a/AnberPorts/scripts/games/Super-Crate-Box
+++ b/AnberPorts/scripts/games/Super-Crate-Box
@@ -3,8 +3,16 @@
 # Release: 2010    Genre: First-person shooter
 
 printf "\e[32mDownloading Super Crate Box ..." > /dev/tty1
+
 wget -q 'https://github.com/krishenriksen/AnberPorts/raw/master/misc/super-crate-box.zip'
-wget -q -O "../Super Crate Box.sh" 'https://raw.githubusercontent.com/krishenriksen/AnberPorts/master/misc/Super%20Crate%20Box.sh'
+if [[ $? -ne 0 ]]; then
+  printf "\e[32mDownloading failed, trying another server ..." > /dev/tty1
+
+  wget 'http://139.196.213.206/releases/anberports/misc/super-crate-box.zip'
+  wget -q -O "../Super Crate Box.sh" 'http://139.196.213.206/releases/anberports/misc/Super%20Crate%20Box.sh'
+else
+  wget -q -O "../Super Crate Box.sh" 'https://raw.githubusercontent.com/krishenriksen/AnberPorts/master/misc/Super%20Crate%20Box.sh'
+fi
 
 printf "\e[32mExtracting ..." > /dev/tty1
 unzip -qq -o super-crate-box.zip -d ../
diff --git a/AnberPorts/scripts/games/Super-Mario-War b/AnberPorts/scripts/games/Super-Mario-War
--- a/AnberPorts/scripts/games/Super-Mario-War
+++ b/AnberPorts/scripts/games/Super-Mario-War
@@ -3,8 +3,17 @@
 # Release: 2008    Genre: Platform-adventure
 
 printf "\e[32mDownloading Super Mario War ..." > /dev/tty1
+
 wget -q 'https://github.com/krishenriksen/AnberPorts/raw/master/misc/super-mario-war.zip'
-wget -q -O "../Super Mario War.sh" 'https://raw.githubusercontent.com/krishenriksen/AnberPorts/master/misc/Super%20Mario%20War.sh'
+if [[ $? -ne 0 ]]; then
+  printf "\e[32mDownloading failed, trying another server ..." > /dev/tty1
+
+  wget 'http://139.196.213.206/releases/anberports/misc/super-mario-war.zip'
+  wget -q -O "../Super Mario War.sh" 'http://139.196.213.206/releases/anberports/misc/Super%20Mario%20War.sh'
+else
+  wget -q -O "../Super Mario War.sh" 'https://raw.githubusercontent.com/krishenriksen/AnberPorts/master/misc/Super%20Mario%20War.sh'
+fi
+
 chmod +x "../Super Mario War.sh"
 
 printf "\e[32mExtracting ..." > /dev/tty1
diff --git a/AnberPorts/scripts/games/System-Shock b/AnberPorts/scripts/games/System-Shock
--- a/AnberPorts/scripts/games/System-Shock
+++ b/AnberPorts/scripts/games/System-Shock
@@ -3,8 +3,16 @@
 # Release: 1994    Genre: First-person shooter
 
 printf "\e[32mDownloading System Shock ..." > /dev/tty1
+
 wget -q 'https://github.com/krishenriksen/AnberPorts/raw/master/misc/system-shock.zip'
-wget -q -O "../System Shock.sh" 'https://raw.githubusercontent.com/krishenriksen/AnberPorts/master/misc/System%20Shock.sh'
+if [[ $? -ne 0 ]]; then
+  printf "\e[32mDownloading failed, trying another server ..." > /dev/tty1
+
+  wget 'http://139.196.213.206/releases/anberports/misc/system-shock.zip'
+  wget -q -O "../System Shock.sh" 'http://139.196.213.206/releases/anberports/misc/System%20Shock.sh'
+else
+  wget -q -O "../System Shock.sh" 'https://raw.githubusercontent.com/krishenriksen/AnberPorts/master/misc/System%20Shock.sh'
+fi
 
 printf "\e[32mPlease copy game 'data' folder to your system-shock/res directory! ..." > /dev/tty1
 unzip -qq -o system-shock.zip -d ../
diff --git a/AnberPorts/scripts/games/The-Clue b/AnberPorts/scripts/games/The-Clue
--- a/AnberPorts/scripts/games/The-Clue
+++ b/AnberPorts/scripts/games/The-Clue
@@ -3,8 +3,16 @@
 # Release: 1994    Genre: First-person shooter
 
 printf "\e[32mDownloading The Clue! ..." > /dev/tty1
+
 wget -q 'https://github.com/krishenriksen/AnberPorts/raw/master/misc/derclou.zip'
-wget -q -O "../The Clue.sh" 'https://raw.githubusercontent.com/krishenriksen/AnberPorts/master/misc/The%20Clue.sh'
+if [[ $? -ne 0 ]]; then
+  printf "\e[32mDownloading failed, trying another server ..." > /dev/tty1
+
+  wget 'http://139.196.213.206/releases/anberports/misc/derclou.zip'
+  wget -q -O "../The Clue.sh" 'http://139.196.213.206/releases/anberports/misc/The%20Clue.sh'
+else
+  wget -q -O "../The Clue.sh" 'https://raw.githubusercontent.com/krishenriksen/AnberPorts/master/misc/The%20Clue.sh'
+fi
 
 printf "\e[32mExtracting ..." > /dev/tty1
 unzip -qq -o derclou.zip -d ../
diff --git a/AnberPorts/scripts/games/The-Ur-Quan-Masters b/AnberPorts/scripts/games/The-Ur-Quan-Masters
--- a/AnberPorts/scripts/games/The-Ur-Quan-Masters
+++ b/AnberPorts/scripts/games/The-Ur-Quan-Masters
@@ -3,8 +3,16 @@
 # Release: 1992    Genre: First-person shooter
 
 printf "\e[32mDownloading The Ur-Quan Masters ..." > /dev/tty1
+
 wget -q 'https://github.com/krishenriksen/AnberPorts/raw/master/misc/uqm.zip'
-wget -q -O "../The Ur-Quan Masters.sh" 'https://raw.githubusercontent.com/krishenriksen/AnberPorts/master/misc/The%20Ur-Quan%20Masters.sh'
+if [[ $? -ne 0 ]]; then
+  printf "\e[32mDownloading failed, trying another server ..." > /dev/tty1
+
+  wget 'http://139.196.213.206/releases/anberports/misc/uqm.zip'
+  wget -q -O "../The Ur-Quan Masters.sh" 'http://139.196.213.206/releases/anberports/misc/The%20Ur-Quan%20Masters.sh'
+else
+  wget -q -O "../The Ur-Quan Masters.sh" 'https://raw.githubusercontent.com/krishenriksen/AnberPorts/master/misc/The%20Ur-Quan%20Masters.sh'
+fi
 
 printf "\e[32mPlease copy games files to your The Ur-Quan Masters directory! ..." > /dev/tty1
 unzip -qq -o uqm.zip -d ../
diff --git a/AnberPorts/scripts/games/They-Need-To-Be-Fed b/AnberPorts/scripts/games/They-Need-To-Be-Fed
--- a/AnberPorts/scripts/games/They-Need-To-Be-Fed
+++ b/AnberPorts/scripts/games/They-Need-To-Be-Fed
@@ -3,8 +3,16 @@
 # Release: 2014    Genre: First-person shooter
 
 printf "\e[32mDownloading They Need To Be Fed ..." > /dev/tty1
+
 wget -q 'https://github.com/krishenriksen/AnberPorts/raw/master/misc/they-need-to-be-fed.zip'
-wget -q -O "../They Need To Be Fed.sh" 'https://raw.githubusercontent.com/krishenriksen/AnberPorts/master/misc/They%20Need%20To%20Be%20Fed.sh'
+if [[ $? -ne 0 ]]; then
+  printf "\e[32mDownloading failed, trying another server ..." > /dev/tty1
+
+  wget 'http://139.196.213.206/releases/anberports/misc/they-need-to-be-fed.zip.zip'
+  wget -q -O "../They Need To Be Fed.sh" 'http://139.196.213.206/releases/anberports/misc/They%20Need%20To%20Be%20Fed.sh'
+else
+  wget -q -O "../They Need To Be Fed.sh" 'https://raw.githubusercontent.com/krishenriksen/AnberPorts/master/misc/They%20Need%20To%20Be%20Fed.sh'
+fi
 
 printf "\e[32mExtracting ..." > /dev/tty1
 unzip -qq -o they-need-to-be-fed.zip -d ../
diff --git a/AnberPorts/scripts/games/Undertale b/AnberPorts/scripts/games/Undertale
--- a/AnberPorts/scripts/games/Undertale
+++ b/AnberPorts/scripts/games/Undertale
@@ -3,8 +3,16 @@
 # Release: 2015    Genre: First-person shooter
 
 printf "\e[32mDownloading Undertale ..." > /dev/tty1
+
 wget -q 'https://github.com/krishenriksen/AnberPorts/raw/master/misc/undertale.zip'
-wget -q -O "../Undertale.sh" 'https://raw.githubusercontent.com/krishenriksen/AnberPorts/master/misc/Undertale.sh'
+if [[ $? -ne 0 ]]; then
+  printf "\e[32mDownloading failed, trying another server ..." > /dev/tty1
+
+  wget 'http://139.196.213.206/releases/anberports/misc/undertale.zip'
+  wget -q -O "../Undertale.sh" 'http://139.196.213.206/releases/anberports/misc/Undertale.sh'
+else
+  wget -q -O "../Undertale.sh" 'https://raw.githubusercontent.com/krishenriksen/AnberPorts/master/misc/Undertale.sh'
+fi
 
 printf "\e[32mPlease copy game files to your undertale directory! ..." > /dev/tty1
 unzip -qq -o undertale.zip -d ../
diff --git a/AnberPorts/scripts/games/Wolfenstein-3D b/AnberPorts/scripts/games/Wolfenstein-3D
--- a/AnberPorts/scripts/games/Wolfenstein-3D
+++ b/AnberPorts/scripts/games/Wolfenstein-3D
@@ -3,11 +3,22 @@
 # Release: 1992    Genre: First-person shooter
 
 printf "\e[32mDownloading Wolfenstein 3D ..." > /dev/tty1
+
 wget -q 'https://github.com/krishenriksen/AnberPorts/raw/master/misc/wolfenstein3d.zip'
-wget -q -O "../Wolfenstein 3D.sh" 'https://raw.githubusercontent.com/krishenriksen/AnberPorts/master/misc/Wolfenstein%203D.sh'
-wget -q -O "../Wolfenstein 3D - Spear of Destiny.sh" 'https://raw.githubusercontent.com/krishenriksen/AnberPorts/master/misc/Wolfenstein%203D%20-%20Spear%20of%20Destiny.sh'
-wget -q -O "../Wolfenstein 3D - Spear of Destiny MP2.sh" 'https://raw.githubusercontent.com/krishenriksen/AnberPorts/master/misc/Wolfenstein%203D%20-%20Spear%20of%20Destiny%20MP2.sh'
-wget -q -O "../Wolfenstein 3D - Spear of Destiny MP3.sh" 'https://raw.githubusercontent.com/krishenriksen/AnberPorts/master/misc/Wolfenstein%203D%20-%20Spear%20of%20Destiny%20MP3.sh'
+if [[ $? -ne 0 ]]; then
+  printf "\e[32mDownloading failed, trying another server ..." > /dev/tty1
+
+  wget 'http://139.196.213.206/releases/anberports/misc/wolfenstein3d.zip'
+  wget -q -O "../Wolfenstein 3D.sh" 'http://139.196.213.206/releases/anberports/misc/Wolfenstein%203D.sh'
+  wget -q -O "../Wolfenstein 3D - Spear of Destiny.sh" 'http://139.196.213.206/releases/anberports/misc/Wolfenstein%203D%20-%20Spear%20of%20Destiny.sh'
+  wget -q -O "../Wolfenstein 3D - Spear of Destiny MP2.sh" 'http://139.196.213.206/releases/anberports/misc/Wolfenstein%203D%20-%20Spear%20of%20Destiny%20MP2.sh'
+  wget -q -O "../Wolfenstein 3D - Spear of Destiny MP3.sh" 'http://139.196.213.206/releases/anberports/misc/Wolfenstein%203D%20-%20Spear%20of%20Destiny%20MP3.sh'
+else
+  wget -q -O "../Wolfenstein 3D.sh" 'https://raw.githubusercontent.com/krishenriksen/AnberPorts/master/misc/Wolfenstein%203D.sh'
+  wget -q -O "../Wolfenstein 3D - Spear of Destiny.sh" 'https://raw.githubusercontent.com/krishenriksen/AnberPorts/master/misc/Wolfenstein%203D%20-%20Spear%20of%20Destiny.sh'
+  wget -q -O "../Wolfenstein 3D - Spear of Destiny MP2.sh" 'https://raw.githubusercontent.com/krishenriksen/AnberPorts/master/misc/Wolfenstein%203D%20-%20Spear%20of%20Destiny%20MP2.sh'
+  wget -q -O "../Wolfenstein 3D - Spear of Destiny MP3.sh" 'https://raw.githubusercontent.com/krishenriksen/AnberPorts/master/misc/Wolfenstein%203D%20-%20Spear%20of%20Destiny%20MP3.sh'
+fi
 
 printf "\e[32mPlease copy game files to your ecwolf directory! ..." > /dev/tty1
 unzip -qq -o wolfenstein3d.zip -d ../
diff --git a/AnberPorts/scripts/games/World-War-II-GI b/AnberPorts/scripts/games/World-War-II-GI
--- a/AnberPorts/scripts/games/World-War-II-GI
+++ b/AnberPorts/scripts/games/World-War-II-GI
@@ -3,8 +3,16 @@
 # Release: 1999    Genre: First-person shooter
 
 printf "\e[32mDownloading World War II GI ..." > /dev/tty1
-wget -q 'https://github.com/krishenriksen/AnberPorts/raw/master/misc/world-war-ii-gi.zip'
-wget -q -O "../World War II GI.sh" 'https://raw.githubusercontent.com/krishenriksen/AnberPorts/master/misc/World%20War%20II%20GI.sh'
+
+wget 'https://github.com/krishenriksen/AnberPorts/raw/master/misc/world-war-ii-gi.zip'
+if [[ $? -ne 0 ]]; then
+  printf "\e[32mDownloading failed, trying another server ..." > /dev/tty1
+
+  wget 'http://139.196.213.206/releases/anberports/misc/world-war-ii-gi.zip'
+  wget -q -O "../World War II GI.sh" 'http://139.196.213.206/releases/anberports/misc/World%20War%20II%20GI.sh'
+else
+  wget -q -O "../World War II GI.sh" 'https://raw.githubusercontent.com/krishenriksen/AnberPorts/master/misc/World%20War%20II%20GI.sh'
+fi
 
 printf "\e[32mPlease copy game files to your World War II GI directory! ..." > /dev/tty1
 unzip -qq -o world-war-ii-gi.zip -d ../
